title: AIxGRC
description: Responsible AI Governance in Practice
theme: jekyll-theme-primer # still allows fallbacks
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
